### ISSUE TITLE
Make sign-up for newsletter a pop-up on the blog

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#1134]
### Description

We have lots of people coming to read our blog posts but they don't necessarily engage with more content. It would be nice to encourage more people to sign-up for our newsletter. The current it pretty passive. How about try to do a pop-up on each blog post that encourages people to 'Keep up to date on Node-RED and FlowFuse, Sign-up for our newsletter'.  The pop-up could be to the right side of the blog post so it doesn't overlap with the content too much.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett, I was checking out HubSpot because it allows us to add some filters to whom this pop-up is displayed, and there's an easy way to implement and track directly from there.

There's a gallery with a few options, I think [this might work](https://drive.google.com/open?id=1c-mpoHI4TmVML2KYRbS6NqBWhM2HHuE5&usp=drive_fs). It's one of the less intrusive options I found, as it allows the user to keep reading.

I had to publish it to be able to record my screen, but I have already unpublished it.

It's set up to be shown only once every two weeks to the same user, as long as they're "unknown" (meaning: not a contact). It's triggered after 7 seconds or when the user reaches 80% of the content, and it's configured to display exclusively on blog pages. We can customize any of these settings, including the message and colors, as desired.

You can check out the configuration [here](https://app-eu1.hubspot.com/calls-to-action/26586079/edit/80178545635/content). It also has a mobile version.

**Comment by iskerrett** [comment]
Looks good. Lets give it a try.

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett it's published now 😃
