### ISSUE TITLE
Theme for release posts

### ISSUE THREAD

**Issue by sammachin** [flowforge/website#147]
### Description

Our release posts will be accompanied by a short video, published on our You Tube channel.
The format of the blog post is for the video to be first on the page, however this means that the default generated image and then the video pushes all the text way down the page.

Create a custom template (or modify the existing one) that allows an embedded YT video to be used instead of the header image on the page

**Comment by knolleary** [comment]
We should modify the existing template to support this, rather than create a new one.

The current logic is here: https://github.com/flowforge/website/blob/main/src/_includes/layouts/post.njk#L28

If the post includes an `image` property in its front-matter, that will be used, otherwise it falls back to the auto-generated image.

I suggest modifying that logic so that if the post has a `video` property (a youtube video ID or url... whatever makes most sense) it gets added in preference to the others.

The blog index page also has [similar logic](https://github.com/flowforge/website/blob/main/src/_includes/layouts/post.njk#L28) to use the post's own image or fallback to the generated one. I propose we don't touch that - it would be odd to have the video as the thumbnail on the index page. In which case the logic there can stay as-is.
