### ISSUE TITLE
Product comparison page unclear on 'configurable infrastructure' and 'FlowForge Managed'

### ISSUE THREAD

**Issue by knolleary** [flowforge/website#159]
### Description

Feedback on the product page.

The Configurable Infrastructure and FlowForge Managed items aren't clear on what they mean.

<img width="977" alt="image" src="https://user-images.githubusercontent.com/51083/184392990-9a27c50e-1033-4396-b063-b62ef93ac025.png">

**Comment by ZJvandeWeg** [comment]
@sammachin @joepavitt Can you post an update on this issue?

**Comment by sammachin** [comment]
These items were a result to the change from the original proposal to have the 4 versions with the switch between self hosted and FlowForge managed.

It comes down to the following:
With Community Edition you have to manage the underlying infrastructure yourself, eg the host, Docker, K8s etc. 
However because of this you can also configure the infrastructure to your own requirements, container sizes, additional packages in the stack etc.
With Cloud Edition FlowForge Manage that infrastructure, but the tradeoff there is that you can only take the stacks that we make available.
Enterprise Edition depends on how it is deployed and the commercial agreement, The customer could choose to manage the infrastructure themselves just like community edition on their own servers, or we could provide a dedicated cluster that we manage on AWS like Cloud Edition.
Because this instance is dedicated to the customer there is more scope to  configure the stacks to that customers requirements, either themselves on their own servers or if we are managing it then via a professional services type of arrangement.

I'm not sure how to distill that down into simpler one liners for a table right now but I think setting out the background is a good start to the conversation

**Comment by knolleary** [comment]
I think there are some super simple changes that remove the unclear parts. This page doesn't need to get into all the nuance - the point is essentially "who runs the platform".

In the interests of improving the clarity of the page, and it being 3 weeks since this feedback was provided by a key stakeholder, I've raised #171 to address it.
