### ISSUE TITLE
Older Handbook files cause conflicts

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#331]
### Current Behavior

When the website runs the `copy_handbook` script (note this will be an issue in the docs too) any edited files are copied into the `website/src/handbook` folder and replace any conflicting files.

In some cases, files are deleted or moved within our handbook, but the copy script _does not_ remove them from the `website/src/handbook` folder. In rare cases, this can cause conflicts where two files want to share the same permalink, e.g.:

```
Problem writing Eleventy templates: (more in DEBUG output)
> Output conflict: multiple input files are writing to `_site/handbook/development/contributing/index.html`. Use distinct `permalink` values to resolve this conflict.
  1. ./src/handbook/development/contributing/index.md
  2. ./src/handbook/development/contributing.md
```

In this case, the newly created `/development/contributing/index.md` conflicts in URL with the old, and now removed, `/development/contributing.md`.

Short-term fix for anyone facing this is:
1. Remove **_just the folders_** in `website/src/handbook`
2. Restart the website server

### Expected Behavior

If I remove a file from the `handbook` repository/source, then that should be reflected in the copied content in `website/src/handbook`

**Solution:** In our `copy_handbook.js` script, clear all contents of `website/src/handbook` (except for `handbook.json`) before copying the new contents.

**Comment by ZJvandeWeg** [comment]
@knolleary Is there a reason not to merge the handbook repository and the website repository?

**Comment by knolleary** [comment]
I originally chose to keep it separate as we wanted the handbook to be a Thing in its own right that happens to be cross-published to the website, rather than the handbook be just one section of the website. It makes it easy to find rather than being buried in a subfolder of the website repo.

I feel that merging them would lose some of the "specialness" of the Handbook.

That's my case for keeping them separate. I can see that merging them would remove the need for the automation for people who need to build the website routinely.. although that is in theory a smaller subset of people than who we'd want editing the handbook regularly.

Anyway... spent too long trying to put this comment together. I could probably have fixed the automation in the same time 😄

**Comment by joepavitt** [comment]
> Is there a reason not to merge the handbook repository and the website repository?

There is no requirement to have the website running or cloned in order to edit the Handbook.

That requirement only comes into play if you want to run the handbook locally and view it embedded into the website to test, which isn't necessary in most cases.

By grouping them together, it makes the clone and editing of the handbook feel heavier imo, although I guess doesn't _force_ users to actually use any of the website code that is there.
