### ISSUE TITLE
SEO: Soft 404

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#335]
### Current Behavior

> Page indexing issues detected in submitted URLs for flowforge.com
> 
> To the owner of flowforge.com:
> 
> Search Console has identified that your site is affected by 1 Page indexing issue(s). The following issues were found on your site.
> 
> Top Issues
> 
> Soft 404
> We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search.

This is our `404.html` page. 

### Expected Behavior

Need to ensure we return HTTP 404 response too.

**Comment by knolleary** [comment]
I think this is a little tricky.

If you go to any invalid page on your site (eg http://flowforge.com/aioahwgoihawgoih ) then you get a proper 404 response code and are shown our 404 page.

If you navigate straight to the 404 page itself ( http://flowforge.com/404.html ) then you see the 404 page, but get a regular 200 status code. This is because you are navigating to a page that exists... it just happens to say 404 on it.

To my knowledge, GH pages doesn't provide any way to set custom response codes on individual *existing* pages.

Given we don't have anything that links explicitly to the url I don't think we would want it to appear on the site index (which is what I assume this report is coming from?). So one approach would be to find a way to prevent it trying to index that page.

**Comment by joepavitt** [comment]
> Given we don't have anything that links explicitly to the url I don't think we would want it to appear on the site index (which is what I assume this report is coming from?). So one approach would be to find a way to prevent it trying to index that page.

Sensible

**Comment by knolleary** [comment]
#345 raised to remove 404 from site index

**Comment by joepavitt** [comment]
Closed by https://github.com/flowforge/website/pull/387
