### ISSUE TITLE
Update tagline in our corporate graphics

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#456]
### Description

 I need to update our social media profiles with the new messaging around DevOps for Node-RED. I would like to update the images we use on these accounts to change the take line from 'Collaborate, low-code, Integration & Automation' to 'DevOps for Node-RED'.  

I have attached mock-ups I created from the ai file on the Goole drive called Social Media Banners.ai. However, I can't actually change the ai file. Can someone help here.

![1](https://user-images.githubusercontent.com/36051834/220955493-f421862f-9398-4dd1-9b61-57193168c40a.png)
![3](https://user-images.githubusercontent.com/36051834/220955618-0b46a9c3-3a8d-4b9b-b4c2-50ab5d7219d1.png)

**Comment by iskerrett** [comment]
@joepavitt any update on this?

**Comment by joepavitt** [comment]
Have updated the OGL image in #490, have also updated Twitter & YouTube Profiles too.

**Comment by joepavitt** [comment]
raw files are in here: https://drive.google.com/drive/u/1/folders/1WgtSJBuKYTFbfqXqT8uhAS66OcsYdhf3

**Comment by iskerrett** [comment]
I actually already have updated the Twitter and LinkedIn profiles.

**Comment by joepavitt** [comment]
> I actually already have updated the Twitter and LinkedIn profiles.

I've updated them with my version of the header with the correct fonts and centred text

**Comment by iskerrett** [comment]
Shouldn't we agree on a version?

**Comment by joepavitt** [comment]
> Shouldn't we agree on a version?

Okay, but they were updated without agreement before this anyway, with the versions you attached in this issue? I then updated the images as requested, and published.

**Comment by iskerrett** [comment]
When I initially opened the issue, I was just asking for help updating the .ai file since I don't have Photoshop. I was hoping I could actually do this update without requiring your time since I know you have a lot on the go. Unfortunately, it seems that is not the case.

**Comment by joepavitt** [comment]
Just to clarify this...

You asked for help updating the .ai file to include the taglines. I did this (its also updated in Google Drive). I wouldn't have just been able to take the images you've produced (which are raster images, i.e. png/jpg) and update the .ai files (which is vector-based, i.e. svg), the .ai file needed to be updated directly. It maintains all of the individual elements, layers, etc. and makes it easily transferrable across the other socials assets in that file (e.g. YouTube Video Thumbnails)

I exported the updated vector file to .jpg for use on the social sites, because, given that you don't have Illustrator, you wouldn't have been able to do that yourself.

I'm not sure how I am meant to be able to help, and do those things, without it taking up my time?

If you would like a Photoshop and/or Illustrator license, then we can probably just add you to the Adobe Licenses. It would certainly benefit for situations like this, although generally, I've always worked in teams where the Designers do the design work, e.g., creating assets and use the respective design tools. If you're not versed in Photoshop or Illustrator, then they can get quite messy, quite quickly.

I would be cautious about public-facing design assets being created by non-designers, but I appreciate the attempt at balancing the workload. This will be less of an issue once our new Visual Designer is on board and can also help with these tasks.
