### ISSUE TITLE
Page: Roadmap Design Review

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#594]
### Description

Our new "Roadmap" page was recently published: https://github.com/flowforge/website/pull/590

Whilst it's functional, would be great to have a review of this from a designers eye, and work out how we can better communicate what we have in the pipeline (and encourage votes), what we are actively working on) and then linking to recent blog posts/announcements for recent version releases.

Inspirations:
- https://posthog.com/roadmap
- https://roadmap.balena.io/?

**Comment by Yndira-FlowForge** [comment]
@joepavitt @MarianRaphael How about this?

(Don't mind the "features" in the cards, or the "latest posts", it's just placeholder text)

Didn't want to add the red because the coloured spaces are too big and it was too much. At first we had the OG image with the pastel colours, but those are too soft...

![Roadmap](https://github.com/flowforge/website/assets/129537638/c76eaafe-f1f1-4d30-b02f-217070b3ec69)

**Comment by MarianRaphael** [comment]
I really like the design! Just one small suggestion: please remove the voting option from the "In Progress" column. If an item is already in progress, we've made a development decision. However, people should still have the option to view the progress if they wish.

**Comment by Yndira-FlowForge** [comment]
> please remove the voting option from the "In Progress" column

@MarianRaphael it would be like this


![Image](https://github.com/flowforge/website/assets/129537638/9439c84c-dd13-4cb2-b246-a5f55db35a96)
