### ISSUE TITLE
Top-level navigation should have a landing page

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#638]
### Description

We should be creating landing pages for our top-level navigation menu items.

For example,
www.flowforge.com/product
www.flowforge.com/soutions
www.flowforge.com/company
www.flowforge.com/resources

**Comment by joepavitt** [comment]
Just looking back over this as it overlaps somewhat with the top-level nav stuff I'm doing at the moment. 

There are two parts to this:

- Landing content for if someone navigates to that URL
- Having our top-level navigation option navigate to these new landing pages.

For the latter, for content where you have a dropdown as we do, this is generally not good practice to have it a link too, as it both operates as a button _and_ a hover to open dropdown. 

The click would then cause a page refresh, to then just be presented with the same options as before, have to move their mouse further in order to get to the link/content they would have been looking for in the first place.

**Comment by joepavitt** [comment]
Just reviewing older tasks - both @Yndira-FlowForge and I agree that this is not necessary as it's not a standard thing to do with navigation/dropdown given that means those pieces of text operate as both buttons _and_ hover items to open a menu.
