### ISSUE TITLE
New customer story

### ISSUE THREAD

**Issue by iskerrett** [flowforge/website#645]
### Description

We want to start publishing stories about companies using Node-RED. This is the first draft of a manufacturing company in the US. The company can not be named.

https://docs.google.com/document/d/1BDSkrhFNe6aB4bCfs13vPzZ1euSO2OY4wz3kFWjceLE/edit?usp=sharing

**Comment by joepavitt** [comment]
Objective: Legitimise Node-RED &FlowForge. Show Node-RED is _not_ just a PoC tool. We need to turn around that perception. We need to be showing what people are doing with Node-RED in the real world.

Longer term: Customer stories under the "product". Similar structure to blog, will grow examples.

**Comment by Yndira-FlowForge** [comment]
References:
[HiveMQ](https://goo.gl/maps/6pY8UgJqthAtqiKp7)
[Confluent](https://www.confluent.io/customers/)

**Comment by iskerrett** [comment]
fwiw, the text in the Google doc has been approved by the customer. Once we have a design for the page, we can use this text for our first customer story.

**Comment by Yndira-FlowForge** [comment]
Hi,

Considering the references we have, I've designed a couple of options.

**For the case studies general page:**

1. Using the same layout as the blog page
<img width="1438" alt="Screenshot 2023-04-24 at 15 03 18" src="https://user-images.githubusercontent.com/129537638/234004597-75bec7c4-2c30-45b1-959f-621365c6cd7e.png">

2. Adding a header with a short sentence
<img width="1440" alt="Screenshot 2023-04-24 at 15 03 06" src="https://user-images.githubusercontent.com/129537638/234004814-372caaf1-1ccb-461a-9226-24ca4173c31e.png">

**For each case page:**

1. "Quote" in gray, which blends with all the content. It works well if we don't want to highlight it anymore than this.
<img width="1437" alt="Screenshot 2023-04-24 at 15 03 40" src="https://user-images.githubusercontent.com/129537638/234005342-dcdaf29d-3958-4083-b7ff-541f31cba19b.png">

2. Quote in red, if we want it to pop and add some variations to the layout.
<img width="1438" alt="Screenshot 2023-04-24 at 15 03 28" src="https://user-images.githubusercontent.com/129537638/234005604-ae9360d5-999f-46d3-a8d4-6d9785c52a00.png">


I think a photo could work better than a graphic, but I'm not so sure what kind of picture I can use. @iskerrett, could you share what they manufacture? The image in the proposals can't be used since it shows people's faces, and we don't have the license to use it, but I think something like this would work really well. Is there any chance of the customer sharing an image of their own?

For the text, I've highlighted some phrases in bold, to make it easier to scan.

I'm not sure if I highlighted the right info, or if the "quote" is meaningful enough for the purpose of this case study; and for the "Challenge", "Solution" and "Results" section, I took a few phrases from the text. Please check it all out and let me know if it works as it is.


**Over here, simple prototypes for both options:**
[Option 1](https://www.figma.com/proto/hXDN5PnY3TmeQSv3n7Hna5/FlowForge-Website?page-id=0%3A1&node-id=1431-11094&viewport=-2635%2C4921%2C0.5&scaling=min-zoom&starting-point-node-id=1431%3A11094&show-proto-sidebar=1)
[Option 2](https://www.figma.com/proto/hXDN5PnY3TmeQSv3n7Hna5/FlowForge-Website?page-id=0%3A1&node-id=1433-11297&viewport=-2635%2C4921%2C0.5&scaling=min-zoom&starting-point-node-id=1433%3A11297&show-proto-sidebar=1)

**Comment by joepavitt** [comment]
I like the image style, we can use anything from Adobe Stock too, with first case, it's an anonymous customer, so that should be fine.

In second story to come, we have permission to say whom, so can make something a little bespoke.

**Comment by joepavitt** [comment]
For the general page, I know I built it, but I don't like the blue header with cloud background on these kind of pages so would like us to start steering away from them. They were inherited from template.

Would be great to have some free thinking here, please do experiment outside of the constraints of what we already have in terms of design.

Iteration 1 can be the re-use blog style for now, but would be great for design to challenge our existing status quo

**Comment by Yndira-FlowForge** [comment]
Hi.

For the general page, thinking outside the blog template, I believe for our first story something like this could work, bringing a sneak peak of the card with the highlights of the case study (I changed the bg color of the card in the page for each case to match it).
<img width="1432" alt="Screenshot 2023-04-25 at 16 30 45" src="https://user-images.githubusercontent.com/129537638/234310411-9fd94bcc-e28f-4ede-9fa9-bf786c906a39.png">

If we'd like to maintain that sneak peak, when we add more case studies, it would look like this:
<img width="1432" alt="Screenshot 2023-04-25 at 16 31 09" src="https://user-images.githubusercontent.com/129537638/234311262-e85fb23e-7b94-4fed-a28f-739262d30abf.png">

And if we don't, maybe use it now that we only have one story, and when we add more, it would look like this
<img width="1438" alt="Screenshot 2023-04-25 at 16 37 57" src="https://user-images.githubusercontent.com/129537638/234312033-1bb851f0-5960-4218-9ce3-5d8ba80909de.png">

**Comment by Yndira-FlowForge** [comment]
Another option for the last case (without the sneak peak to the highlights)
<img width="1294" alt="Screenshot 2023-04-25 at 20 05 00" src="https://user-images.githubusercontent.com/129537638/234363985-0f0b3055-053c-4207-a669-4797bf444e39.png">

**Comment by iskerrett** [comment]
I am completely fine with all the directions you provided. I trust the two of you to pick the best one. A couple of comments:
- I like the bold but I think there might be a bit too much. I would reduce by at least a third.
- In future stories we will be able to use a logo so we need a design that can highlight a corporate logo and url.

For the first one, the customer will not provide an image and we shouldn't even try to match an image with the customer. The ones you have selected look fine so please select something that we can get the correct permission to use.

**Comment by joepavitt** [comment]
> Another option for the last case (without the sneak peak to the highlights)

this one gets my vote for when we have multiple stories to publish.

but 1. [here](https://github.com/flowforge/website/issues/645#issuecomment-1520166690) gets my vote as a start when we only have 1.

**Comment by Yndira-FlowForge** [comment]
@joepavitt did you see [this other version](https://user-images.githubusercontent.com/129537638/234310411-9fd94bcc-e28f-4ede-9fa9-bf786c906a39.png) for only 1 story-0

**Comment by joepavitt** [comment]
> did you see [this other version](https://user-images.githubusercontent.com/129537638/234310411-9fd94bcc-e28f-4ede-9fa9-bf786c906a39.png) for only 1 story?

I did, but feel like you're showing _too much_ at that point? not enticing for a user to read more?

**Comment by Yndira-FlowForge** [comment]
> but 1. https://github.com/flowforge/website/issues/645#issuecomment-1520166690 gets my vote as a start when we only have 1.
> I like the bold but I think there might be a bit too much. I would reduce by at least a third.
> The ones you have selected look fine so please select something that we can get the correct permission to use.

Ok, so, for the story we already have, it would be [like this](https://www.figma.com/proto/hXDN5PnY3TmeQSv3n7Hna5/FlowForge-Website?page-id=0%3A1&node-id=1431-11094&viewport=-400%2C2625%2C0.25&scaling=min-zoom&starting-point-node-id=1431%3A11094&show-proto-sidebar=1). We have the license for this image ;)

> In future stories we will be able to use a logo so we need a design that can highlight a corporate logo and url.

I made some changes. When we add more stories and client info it would be [like this](https://www.figma.com/proto/hXDN5PnY3TmeQSv3n7Hna5/FlowForge-Website?page-id=0%3A1&node-id=1476-8272&viewport=-400%2C2625%2C0.25&scaling=min-zoom&starting-point-node-id=1476%3A8272&show-proto-sidebar=1)

**Comment by Yndira-FlowForge** [comment]
> Do you know what they are making in the image?

I don't, thought you might... It came from [this page](https://stock.adobe.com/es/images/engineer-using-laptop-computer-for-control-automatic-robotic-arm/133904646), it doesn't say much in the description

**Comment by iskerrett** [comment]
ok, it looks fine.

Are we ready to publish this article?

**Comment by joepavitt** [comment]
> Are we ready to publish this article?

We need to dev the new section for the site, so not ready - is this high priority? If so, can try and get done this afternoon, otherwise it was going to be my first task for Tuesday

**Comment by joepavitt** [comment]
@Yndira-FlowForge the base templating has been pushed to https://github.com/flowforge/website/tree/645-customer-stories - would be great if you could step in to populate the content (article/page, challenges, etc. & image)

**Comment by Yndira-FlowForge** [comment]
Hi @joepavitt done!
