### ISSUE TITLE
Cookie consent on every page

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/website#72]
### Current Behavior

Prompted to allow consent of cookies on every page. Happening on Android, Chrome

### Expected Behavior

Accepting once should save the state.

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS: Android
- Browser: Chrome

**Comment by ZJvandeWeg** [comment]
Got this report from Joe through Slack, didn't reproduce myself either.

**Comment by joepavitt** [comment]
hmmm... no longer happening for me either. I message ZJ last night as it was an issue on my phone. Will close for now.

**Comment by joepavitt** [comment]
Okay, it's definitely happening to me, although no with Chrome on a Mac. I've noticed it's when Chrome flags the site as "Not Secure". Sometimes it does that, and sometimes it doesn't. Any ideas @knolleary or @hardillb?

https://user-images.githubusercontent.com/99246719/161710567-9dd2a914-ed40-4a79-90bf-9f65347c21d8.mp4

**Comment by sammachin** [comment]
GitHub Pages is serving the content for `http://flowforge.com` rather than redirecting to `https://` so the insecure thing will depend on if/how your Chrome is requesting the URL, I can't seem to make my Chrome load the plain http version though.

I can load plain http if using incognito mode however the cookie warning doesn't re-appear for the duration of that session
