### ISSUE TITLE
Clicking **About** results in 404, clicking **Values** goes nowhere

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/website#87]
### Current Behavior

On the page https://flowforge.com/handbook/company/ ...
* Clicking **About** results in 404
* Clicking **Values** does nothing

### Steps To Reproduce

* Navigate to https://flowforge.com/handbook/company/ 
* click the **About** link
* click the **Values** link

### Environment

- FlowForge version: NA
- Node.js version: NA
- npm version: NA
- Platform/OS: cloud
- Browser: chrome

**Comment by knolleary** [comment]
Fixes for this will be in the flowforge/handbook repository as that's where the content for those pages live.

**Comment by Steve-Mcl** [comment]
@knolleary Joe asked for it to be raised here

**Comment by knolleary** [comment]
No problem - just pointing out the content of the pages in question aren't in this repo.

This might be a bug in the way the website repo generates the HTML from the markdown source - and has to remap links. But occams razor suggests the the broken links are in the origin src :)

**Comment by Steve-Mcl** [comment]
Also noticed this...

![image](https://user-images.githubusercontent.com/44235289/162157595-657e5495-2b17-4ee8-adfa-53271f13ed15.png)

maybe related #84 ?

**Comment by joepavitt** [comment]
okay, a little gotcha for the future, and one we may want to work out a cleaner `copy_handbook.sh` for:

The files in the `/website/handbook/` folder:
<img width="165" alt="Screenshot 2022-04-07 at 17 13 05" src="https://user-images.githubusercontent.com/99246719/162249354-cd73749c-0b64-42ad-ab05-2699d6288209.png">

The files in the `handbook` repo on `main`:
<img width="149" alt="Screenshot 2022-04-07 at 17 13 14" src="https://user-images.githubusercontent.com/99246719/162249301-d0bd91dc-7731-4937-a304-4590574fe3af.png">

This is because those files used to exist, and when `copy_handbook` runs, it just copies over the latest content, without removing any files that may no longer be present. The solution is a fix in the `handbook` repo, but we may want to use this issue in order to come up with a cleaner method in `copy_handbook.sh`
