### ISSUE TITLE
Past webinar showing as upcoming

### ISSUE THREAD

**Issue by Yndira-FlowForge** [flowforge/website#893]
### Description

The live site shows this (and it's wrong because today is 23rd and it should be in the past webinars section):
<img width="1189" alt="Screenshot 2023-06-23 at 13 47 01" src="https://github.com/flowforge/website/assets/129537638/7e422979-4b96-478c-8dda-6ca0cd3c6c42">

But locally, it looks as it's supposed to:
<img width="1798" alt="Screenshot 2023-06-23 at 13 47 12" src="https://github.com/flowforge/website/assets/129537638/cdcfe61b-4c2e-449f-a939-92014240d5ef">

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by Yndira-FlowForge** [comment]
Hi @knolleary I know you worked on this for the past webinar #779 but I'm not sure if it's related... Would you mind taking a look, please?

**Comment by knolleary** [comment]
I do not see the banner when I access the page... although I think it was there this morning.

I wonder if this is timezone related; the code currently just checks if the event is the either 'today' or in the future. The concept of 'today' will be based on the server's timezone so may continue to show the banner the following day for some users.

The fix ought to be to not only check the day, but also the time.

**Comment by joepavitt** [comment]
> I do not see the banner when I access the page... although I think it was there this morning.

Yndira removed it [here](https://github.com/flowforge/website/pull/892) as we have no upcoming Webinar at the moment

**Comment by knolleary** [comment]
The webinar page is statically generated whenever the site is rebuild. What is on the webinar page will depend on when the site was last generated. If the site isn't updated, then it will continue serving the same HTML as the day before.

The webinar page now looks correct because we've deployed other updates to the site today - so the page has been rebuilt and correctly put yesterday's webinar into the past.

We don't really want to make the whole webinar page dynamically generated just for this; a more straightforward fix would be to schedule the build site action to run every night automatically - ensuring everything is freshly generated.
